-- Defense Enclave Society / Supabase schema
create extension if not exists pgcrypto;
create table if not exists public.society (id uuid primary key default gen_random_uuid(), name text not null, phone text, email text, address text, latitude numeric, longitude numeric, description text, created_at timestamptz default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text not null, email text not null unique, phone text, house_no text not null, address text, profile_photo text, role text not null default 'member' check (role in ('member','admin')), created_at timestamptz default now());
create table if not exists public.works (id uuid primary key default gen_random_uuid(), title text not null, description text, status text not null check(status in ('Ongoing','Pending','Completed')), progress integer default 0 check(progress between 0 and 100), target_date date, completed_date date, amount numeric default 0, image_url text, created_at timestamptz default now());
create table if not exists public.complaints (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, category text not null, subject text not null, description text not null, contact_phone text, contact_email text, attachment_url text, status text not null default 'Submitted' check(status in ('Submitted','In Progress','Resolved','Rejected')), admin_comment text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.events (id uuid primary key default gen_random_uuid(), title text not null, description text, event_date timestamptz not null, location text, image_url text, created_at timestamptz default now());
create table if not exists public.gallery (id uuid primary key default gen_random_uuid(), title text, image_url text not null, event_id uuid references public.events(id) on delete set null, uploaded_by uuid references public.profiles(id) on delete set null, created_at timestamptz default now());
create table if not exists public.announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, published_at timestamptz default now(), is_active boolean default true);
create table if not exists public.finances (id uuid primary key default gen_random_uuid(), month_start date not null, income numeric default 0, expense numeric default 0, maintenance_expense numeric default 0, description text, created_at timestamptz default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), title text not null, status text not null default 'Pending' check(status in ('Pending','In Progress','Completed')), due_date date, assigned_to uuid references public.profiles(id) on delete set null, created_at timestamptz default now());

alter table public.society enable row level security; alter table public.profiles enable row level security; alter table public.works enable row level security; alter table public.complaints enable row level security; alter table public.events enable row level security; alter table public.gallery enable row level security; alter table public.announcements enable row level security; alter table public.finances enable row level security; alter table public.tasks enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
create policy "public society" on public.society for select using (true);
create policy "public members safe fields" on public.profiles for select using (true);
create policy "own profile update" on public.profiles for update using (auth.uid()=id) with check(auth.uid()=id);
create policy "own profile insert" on public.profiles for insert with check(auth.uid()=id);
create policy "public works" on public.works for select using (true); create policy "admin works" on public.works for all using (public.is_admin()) with check(public.is_admin());
create policy "public events" on public.events for select using (true); create policy "admin events" on public.events for all using (public.is_admin()) with check(public.is_admin());
create policy "public gallery" on public.gallery for select using (true); create policy "admin gallery" on public.gallery for all using (public.is_admin()) with check(public.is_admin());
create policy "public announcements" on public.announcements for select using (is_active=true or public.is_admin()); create policy "admin announcements" on public.announcements for all using (public.is_admin()) with check(public.is_admin());
create policy "members own complaints" on public.complaints for select using (auth.uid()=user_id or public.is_admin()); create policy "members create complaints" on public.complaints for insert with check(auth.uid()=user_id); create policy "admin complaint update" on public.complaints for update using (public.is_admin()) with check(public.is_admin());
create policy "public finances summary" on public.finances for select using (auth.role() = 'authenticated'); create policy "admin finances" on public.finances for all using (public.is_admin()) with check(public.is_admin());
create policy "members tasks" on public.tasks for select using (auth.role()='authenticated'); create policy "admin tasks" on public.tasks for all using (public.is_admin()) with check(public.is_admin());

insert into public.society(name,phone,email,address,description) values('Defense Enclave Society','+91 98765 43210','contact@defenseenclave.example','Defense Enclave Society, Punjab, India','Residential community portal.') on conflict do nothing;
